### PR TITLE
Minor UI Improvements

### PR DESCRIPTION
**Pull request by Rahuletto**
# Done:
```
✔ Responsive Image Preview
✔ UI Improvements
✔ Ability to open image in new tab
```

### CODE REVIEW

**Comment by Rahuletto** [comment]
# ✔ Responsive Image Preview

Made image preview div to be responsive
| Before | After |
|---|---|
| image | image|

**Comment by Rahuletto** [comment]
# ✔ UI Improvements
Implemented a way so you can easily identify a clickable button (at hover state)
| Clickable | Disabled |
|----------|-----------|
| image | image |

**Comment by Rahuletto** [comment]
# ✔ Ability to open image in new tab
People can click this button to open a image in new tab if they cant zoom in ease. (Only available to Mobile users)

image

Placement:
image

**Comment by armoredvortex** [comment]
Cool UI changes.
Noticed a bug, the zoom slider and new tab button are inaccessible and hidden behind the image on browser window with shorter height.
image

**Comment by Rahuletto** [comment]
Wait shorter height 💀. I never thought about shorter height displays  and the new tab button will be inaccessible for laptops/pc. It's only available for mobile/tablet devices

**Comment by ManorSailor** [comment]
New UI changes looks really nice. Good work!

**Review by ManorSailor — APPROVED** [review]

**Comment by Rahuletto** [comment]
this commit provides ability to view from displays with small height

**Review by armoredvortex — APPROVED** [review]

**Comment by Rahuletto** [comment]
Ready to merge ig

**Pull request merged**
