### PR TITLE
Image files auto listing in python script

### PR DESCRIPTION
**Pull request by Pesc0**
The title says it.
- Updated the README file, removing option to submit dots through issues (how do you add images? plus its manual labor, and opening a pr is basically same effort for the submitter). This removes the option to add images as URLs, since we discussed this would pose issues to moderation.
- The python script could be cleaned up a bit i think. 
- Multi-image support still needs to be implemented js-side.
- I was thinking of adding a `.gitignore` file to hide `dotfiles.js`, but i was not sure if that would break github workflows.

### CODE REVIEW

**Review by mahanla — COMMENTED** [review]
I was thinking of renaming the image tag in the YAML to something like thumbnail, so that the user can specify the thumbnail name in case they want to use another name than the default thumbnail.png/jpg
And then we wouldn't need to rename every image to thumbnail, for the previously submitted themes


Also if you add dotfiles.js to gitingore, then it won't be included in the git repo meaning it will be entirely removed from github. And that would break the website entirely since we are basically using github as our file hosting server

**Comment by armoredvortex** [comment]
Awesome changes!

> I was thinking of adding a .gitignore file to hide dotfiles.js, but i was not sure if that would break github workflows.

The current workflow uses `stefanzweifel/git-auto-commit-action@v4` to auto commit the parsed changes which by default doesn't stage files inside the `.gitignore`. I suppose it can be bypassed by adding the `-f` flag while staging changes but i don't think there's really much of an incentive doing that.

**Review by armoredvortex — APPROVED** [review]

**Comment by Pesc0** [comment]
Renaming an image to thumbnail is optional. we dont need to rename all existing images. to put it simply: if an image is called thumbnail it is put _first_ in the list, otherwise the list is in alphabetical order. I dont see much benefit in the extra flexibility of the file name, nobody is going to see that anyway

> Also if you add dotfiles.js to gitingore, then it won't be included in the git repo meaning it will be entirely removed from github. And that would break the website entirely since we are basically using github as our file hosting server

Right, i was thinking since it gets generated behind the scenes github-side maybe it would still work. Alright we'll do without gitignore.

**Review by mahanla — APPROVED** [review]
Yeah, I think this is enough. I think we can merge this

**Pull request merged**
