### PR TITLE
Categorising to expand the site

### LINKED ISSUE #29: Categorise items to expand the site
# ` Enhancement `

We have high expectations to make this a linux customising centre. This may be the first move towards that.

As the title says, We do wanna categorise things like `dots`, `icons`, `vim configs` and so on.

For this purpose, I moved the image button to an optimal place. Giving room for category icons in the pull request https://github.com/unixporn-dots/unixporn-dots.github.io/pull/28

I'm planning to create a drop-down box to make it easy to navigate through categories

This is a very low priority issue.

### PR DESCRIPTION
**Pull request by Rahuletto**
We are expanding the site by adding more things (like icons, vim configs, etc..) and making this site as an centre for linux customization i think lol.

## What's changed ?
- ### Smooth multi image preview
- ### More categories (referring to issue #29)

### CODE REVIEW

**Comment by Rahuletto** [comment]
I need @Pesc0 to verify the `generateJS.py` file. is there any issues with the changes ??

**Comment by Rahuletto** [comment]
This pull request is under draft because its under work.

## What's coming:
```diff
+ Category Menu
- More entries
- More Categories
+ Shuffle and search in all pages
+ gtk-themes and icons page
+ Pull request template
+ Refactor of generateJS.py
```

**Comment by Rahuletto** [comment]
the Simple_Icons folder is used just for testing categories !! Its not for the production. @ArmoredVortex

**Review by armoredvortex — APPROVED** [review]

**Review by mahanla — APPROVED** [review]

**Comment by Rahuletto** [comment]
I made a commit [496d783](https://github.com/unixporn-dots/unixporn-dots.github.io/pull/41/commits/496d783f5fb789643ef061d289670e5351584aaf) so that you can shuffle the icons cards @mahancoder

**Comment by Rahuletto** [comment]
## What's new ?
- New gtk-themes category with search and shuffle.
- Making `generateJS.py` code smaller by running loops (not in production rn)
- Two new gtk-themes

**Review by armoredvortex — CHANGES_REQUESTED** [review]
The generateJS.py doesn't work as intended at the moment

**Comment by Rahuletto** [comment]
> The generateJS.py doesn't work as intended at the moment

https://github.com/unixporn-dots/unixporn-dots.github.io/pull/41/commits/0e01f241d4f01e90760ffa287dfc6d6a8b441351 works as intended (can you show whats wrong ?)

**Comment by armoredvortex** [comment]
> > The generateJS.py doesn't work as intended at the moment
> 
> [0e01f24](https://github.com/unixporn-dots/unixporn-dots.github.io/commit/0e01f241d4f01e90760ffa287dfc6d6a8b441351) works as intended (can you show whats wrong ?)

image
here's the outfile, it only generates 2 properties

**Comment by Rahuletto** [comment]
this definitely fixes

common python developer's nightmare, indents. just 2 indents broke the code

**Comment by Pesc0** [comment]
Wow its moving fast! I dont have much time, will check the code in a couple of days

**Comment by Rahuletto** [comment]
> Wow its moving fast! I dont have much time, will check the code in a couple of days

This is not going to be pushed immediately, take your time ;)

**Review by armoredvortex — APPROVED** [review]

**Comment by Pesc0** [comment]
Sup. I have refactored generateJS.py, but cant commit to this PR. Perhaps open a dev branch?

**Comment by Rahuletto** [comment]
You can create another pr, it will be pulled to this pr

**Comment by armoredvortex** [comment]
Since this PR is getting gigantic day by day, I suppose the present updates should be merged so as to reduce the conflicts with the main branch

**Pull request merged**
