### PR TITLE
adding the most upvoted rices on r/unixporn

### PR DESCRIPTION
**Pull request by Not-a-web-Developer**
this will be a slowly progressing PR, and help will be appreciated.

as for why, I feel like the rices that appear when you sort r/unixporn by top of all time are popular enough that they should be on the website.

### CODE REVIEW

**Comment by Rahuletto** [comment]
Thank you for the interest in contributing ❤️

**Comment by armoredvortex** [comment]
Please do try to prevent repetition as i have already added a few top rices i suppose.
Awesome work, appreciate your efforts a lot.

**Comment by armoredvortex** [comment]
When are we merging this actually ?

**Comment by armoredvortex** [comment]
Since the progress is like super slow on this PR, i'll just merge the changes from my local repository for now

**Pull request merged**
